[package]
name = "trackflow_program"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
trackflow_lib = { path = "../lib" }
serde = { version = "1.0", features = ["derive"] }
