name: SP1 Proof Generation

on:
  repository_dispatch:
    types: [generate_proof]

jobs:
  generate-proof:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            program/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Generate Proof
        id: generate
        working-directory: ./program
        run: |
          echo '${{ github.event.client_payload.tasks }}' > tasks.json
          cargo run --release tasks.json > proof.json
          PROOF=$(cat proof.json)
          echo "::set-output name=proof::$PROOF" # For backward compatibility
          echo "proof=$PROOF" >> $GITHUB_OUTPUT
          
      - name: Call Vercel API Callback
        run: |
          curl -X POST https://track-flow-app-sp1.vercel.app/api/proof-callback \
            -H "Content-Type: application/json" \
            -d "{\"proof\": ${{ steps.generate.outputs.proof }}, \"taskId\": \"${{ github.event.client_payload.taskId }}\"}" 
          
      - name: Debug Output
        run: |
          echo "TaskId: ${{ github.event.client_payload.taskId }}"
          echo "Proof generated and sent to callback URL" 