name: SP1 Proof Generation

on:
  repository_dispatch:
    types: [generate_proof]

jobs:
  generate-proof:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            program/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Debug client payload
        run: |
          echo "Received tasks: ${{ toJSON(github.event.client_payload.tasks) }}"
          echo "TaskId: ${{ github.event.client_payload.taskId }}"
          
      - name: Generate Proof
        id: generate
        working-directory: ./program
        run: |
          echo '${{ toJSON(github.event.client_payload.tasks) }}' > tasks.json
          cat tasks.json
          cargo run --release tasks.json > proof_output.json || { cat tasks.json; exit 1; }
          cat proof_output.json
          # Fix any JSON formatting issues and ensure it starts with {
          sed -i '1s/^[^{]/\{/' proof_output.json
          PROOF=$(cat proof_output.json)
          # Use GitHub Actions environment file for outputs
          echo "proof<<EOF" >> $GITHUB_OUTPUT
          echo "$PROOF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Call Vercel API Callback
        run: |
          # Prepare a proper JSON payload
          echo "Sending proof data to callback URL"
          TASKID="${{ github.event.client_payload.taskId }}"
          echo "TaskId: $TASKID"
          
          # Format the JSON payload properly
          PROOF_DATA=$(cat ./program/proof_output.json)
          echo "Proof data: $PROOF_DATA"
          
          # Create a temporary JSON file with the full payload
          echo "{\"proof\": $PROOF_DATA, \"taskId\": \"$TASKID\"}" > callback_payload.json
          cat callback_payload.json
          
          # Send to the callback URL
          curl -v -X POST https://track-flow-app-sp1.vercel.app/api/proof-callback \
            -H "Content-Type: application/json" \
            -d @callback_payload.json
          
      - name: Debug Output
        run: |
          echo "TaskId: ${{ github.event.client_payload.taskId }}"
          echo "Proof generated and sent to callback URL" 